<a href="https://colab.research.google.com/github/rohitgupta29/Actionable-NLP/blob/main/CountVectorizer_on_twitter_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dataset - Twitter data from Kaggle. 

Steps - 1. Loaded and cleaned the data.
        2. Used CountVectorizer on it.

In [1]:
import pandas as pd

This Dataset - twitter Hatred data.

In [2]:
train = pd.read_csv("https://raw.githubusercontent.com/rohitgupta29/Datasets/master/NLP/train.csv")

In [3]:
train.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [4]:
#non- racist
sum(train["label"] == 0)

29720

In [5]:
#racist
sum(train["label"] == 1)

2242

In [17]:
import re

#set up punctuations we want to be replaced
REPLACE_NO_SPACE = re.compile("(\.)|(\;)|(\:)|(\!)|(\')|(\?)|(\,)|(\")|(\|)|(\()|(\))|(\[)|(\])|(\%)|(\$)|(\>)|(\<)|(\{)|(\})")
REPLACE_WITH_SPACE = re.compile("(<br\s/><br\s/?)|(-)|(/)|(:).")

In [8]:
!pip install tweet-preprocessor

In [20]:
import preprocessor as p

#its a custom function to clean the dataset 
def clean_tweets(df):
  tempArr = []
  for line in df:
    # send to tweet_processor
    tmpL = p.clean(line)
    # remove puctuation
    tmpL = REPLACE_NO_SPACE.sub("", tmpL.lower()) # convert all tweets to lower cases
    tmpL = REPLACE_WITH_SPACE.sub(" ", tmpL)
    tempArr.append(tmpL)
  return tempArr

In [21]:
#cleaning training data
train_tweet = clean_tweets(train["tweet"])
train_tweet = pd.DataFrame(train_tweet)

In [65]:
#append cleaned tweets to the training data
train["clean_tweet"] = train_tweet

train1 = train.drop(['tweet','id','label'], axis = 1)

train_vectorize = train1.iloc[:5]
train_vectorize

clean_tweet
0  when a father is dysfunctional and is so selfi...
1  thanks for credit i cant use cause they dont o...
2                                bihday your majesty
3            i love u take with u all the time in ur
4                             factsguide society now

In [66]:
from sklearn.feature_extraction.text import CountVectorizer

In [67]:
vectorizer = CountVectorizer()

vectorizer = CountVectorizer(stop_words = 'english')

vectorizer.fit(list(train_vectorize["clean_tweet"]))  
  

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [68]:
vectorizer.vocabulary_

{'bihday': 0,
 'cause': 1,
 'credit': 2,
 'dont': 3,
 'drags': 4,
 'dysfunction': 5,
 'dysfunctional': 6,
 'factsguide': 7,
 'father': 8,
 'kids': 9,
 'love': 10,
 'majesty': 11,
 'offer': 12,
 'pdx': 13,
 'selfish': 14,
 'society': 15,
 'thanks': 16,
 'time': 17,
 'ur': 18,
 'use': 19,
 'vans': 20,
 'wheelchair': 21}

In [70]:
vector = vectorizer.transform(list(train_vectorize['clean_tweet']))
print(vector.shape)
print(type(vector))
print(vector.toarray())
pd.DataFrame(vector.toarray(), columns = vectorizer.get_feature_names())

(5, 22)
<class 'scipy.sparse.csr.csr_matrix'>
[[0 0 0 0 1 1 1 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0]]


bihday  cause  credit  dont  drags  ...  time  ur  use  vans  wheelchair
0       0      0       0     0      1  ...     0   0    0     0           0
1       0      1       1     1      0  ...     0   0    1     1           1
2       1      0       0     0      0  ...     0   0    0     0           0
3       0      0       0     0      0  ...     1   1    0     0           0
4       0      0       0     0      0  ...     0   0    0     0           0

[5 rows x 22 columns]